#cloud-config

##
## This is a fleet cloud-config for etcd node
##

coreos:
    fleet:
        public-ip: $private_ipv4
        metadata: "platform=m1.small,provider=aws,region=us-west-2,disk=ssd,role=etcd"
    units:
        - name: fleet.service
          command: start

# end of cloud-config fleet
