#cloud-config

coreos:
    fleet:
        etcd_servers: "http://127.0.0.1:4001,http://172.17.8.101:4001,http://172.17.8.102:4001,http://172.17.8.103:4001"
    units:    
        - name: setup-etcdctl-env.service
          command: start
          content: |       
              [Unit]
              Description=Setup etcdctl env vars
              Wants=coreos-setup-environment.service
              After=coreos-setup-environment.service
              
              [Service]
              Type=oneshot
              RemainAfterExit=true
              ExecStart=/bin/bash -c "source /etc/profile.d/etcd-envvars.sh; env | grep -E 'ETCD|FLEETCTL' >> /etc/environment"
              
              [Install]
              WantedBy=multi-user.target

# certs for etcd
write_files:
  - path: /etc/profile.d/etcd-envvars.sh
    permissions: 0644
    owner: root
    content: |
      ##########################################################
      # If etcd service is not running locally
      # these env vars are necessary for tools that talk to etcd
      # 
      # make sure this file has the right values and drop it
      # under the /etc/profile.d
      
      # for etcdctl
      export ETCDCTL_PEERS="http://127.0.0.1:4001,http://172.17.8.101:4001,http://172.17.8.102:4001,http://172.17.8.103:4001"
      
      # for fleetctl. Note: FLEETCTL_ENDPOINT only take one url
      export FLEETCTL_ENDPOINT="http://172.17.8.101:4001"
      
      # for skydns
      export ETCD_MACHINES=$ETCDCTL_PEERS
