#cloud-config

##
## This is a cloud-config for docker registry service
##

coreos:
    units:
        - name: registry.service
          command: start
          content: |             
              [Unit]
              Description=Host DNS Register
              Requires=docker.service
              After=docker.service
              
              [Service]
              EnvironmentFile=/etc/environment
              EnvironmentFile=/var/lib/apps/skydns/envvars
              TimeoutStartSec=300
              ExecStartPre=/usr/bin/bash -c "/var/lib/apps/bin/is_loaded registry:latest || /var/lib/apps/bin/dkload registry-latest.tgz"
              ExecStartPre=-/usr/bin/docker rm -f %n
              ExecStart=/usr/bin/bash -c "docker run --rm --name %n -p 80:5000 -v /var/lib/apps-data/registry:/data -v /var/lib/apps/registry:/registry-conf \
                      -e DOCKER_REGISTRY_CONFIG=/registry-conf/config.yml -e SETTINGS_FLAVOR=prod registry:latest"
              ExecStartPost=/var/lib/apps/bin/dns-set 'registry' "%H.${LOCAL_DOMAIN}"
              ExecStopPost=-/var/lib/apps/bin/dns-delete 'registry'
              RestartSec=5
              Restart=always

# end of cloud-config registry
