#cloud-config

##
## This is a cloud-config for skydns service
##
coreos:
    units:
        - name: skydns-install.service
          command: start
          content: |
              [Unit]
              Description=SkyDNS Installer
              Requires=docker.service
              After=docker.service
              
              [Service]
              Type=oneshot
              RemainAfterExit=true
              EnvironmentFile=/var/lib/skydns/envvars
              ExecStart=-/bin/mkdir -p /opt/bin
              ExecStart=/bin/bash -c "[[ -x /opt/bin/skydns ]] || \
                      curl -L -o /opt/bin/skydns ${SKYDNS_CMD_REPO} && chmod 755 /opt/bin/skydns; echo ok"
        - name: skydns.service
          command: start
          content: |
              [Unit]
              Description=skydns
              Requires=skydns-install.service
              After=skydns-install.service
              
              [Service]  
              Type=simple
              Restart=always
              RestartSec=5
              EnvironmentFile=/etc/environment
              EnvironmentFile=/var/lib/skydns/envvars
              # Set skydns configuration in etcd
              ExecStartPre=-/var/lib/apps/bin/set-skydns-config ${SKYDNS_CONFIG}
              ExecStart=/opt/bin/skydns
              # with etcd, skydns may not neet to sync with each other anymore:
              # ExecStartPost=-/var/lib/apps/bin/dns-set x%m.ns.dns ${COREOS_PRIVATE_IPV4}
              # ExecStopPost=-/var/lib/apps/bin/dns-delete x%m.ns.dns
              RestartSec=5
              Restart=always
# end of cloud-config skydns
